//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminPages> AdminPages { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<AdminsLogins> AdminsLogins { get; set; }
        public virtual DbSet<AdminToUsersNews> AdminToUsersNews { get; set; }
        public virtual DbSet<AntiFraudLog> AntiFraudLog { get; set; }
        public virtual DbSet<AppLogs> AppLogs { get; set; }
        public virtual DbSet<BlackList> BlackList { get; set; }
        public virtual DbSet<BlockedUserNum> BlockedUserNum { get; set; }
        public virtual DbSet<BlockIdNumber> BlockIdNumber { get; set; }
        public virtual DbSet<BlockIp> BlockIp { get; set; }
        public virtual DbSet<CardCam> CardCam { get; set; }
        public virtual DbSet<CCData> CCData { get; set; }
        public virtual DbSet<CcDetails> CcDetails { get; set; }
        public virtual DbSet<ChatTimeUse> ChatTimeUse { get; set; }
        public virtual DbSet<CountryList> CountryList { get; set; }
        public virtual DbSet<Currencies> Currencies { get; set; }
        public virtual DbSet<DomainIDToUsers> DomainIDToUsers { get; set; }
        public virtual DbSet<EmployeeManageLevels> EmployeeManageLevels { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<LogCcFaild> LogCcFaild { get; set; }
        public virtual DbSet<LogChatTimeUse> LogChatTimeUse { get; set; }
        public virtual DbSet<LogLastVisit> LogLastVisit { get; set; }
        public virtual DbSet<LogRtc> LogRtc { get; set; }
        public virtual DbSet<NotsAboutCustomers> NotsAboutCustomers { get; set; }
        public virtual DbSet<OnlineUsers> OnlineUsers { get; set; }
        public virtual DbSet<PaymentStatus> PaymentStatus { get; set; }
        public virtual DbSet<PaymentStrings> PaymentStrings { get; set; }
        public virtual DbSet<Planes> Planes { get; set; }
        public virtual DbSet<PlanProperties> PlanProperties { get; set; }
        public virtual DbSet<PlanToPlanproperties> PlanToPlanproperties { get; set; }
        public virtual DbSet<PrepaidBin> PrepaidBin { get; set; }
        public virtual DbSet<Prices> Prices { get; set; }
        public virtual DbSet<RoomConversation> RoomConversation { get; set; }
        public virtual DbSet<SendUsersWriteAboutGetUsers> SendUsersWriteAboutGetUsers { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
        public virtual DbSet<SiteMessages> SiteMessages { get; set; }
        public virtual DbSet<SiteMessagesToLanguages> SiteMessagesToLanguages { get; set; }
        public virtual DbSet<SMSLogs> SMSLogs { get; set; }
        public virtual DbSet<Studios> Studios { get; set; }
        public virtual DbSet<StudiosToGirls> StudiosToGirls { get; set; }
        public virtual DbSet<SupplierToServicePrice> SupplierToServicePrice { get; set; }
        public virtual DbSet<SupportChat> SupportChat { get; set; }
        public virtual DbSet<SupportCorrespondence> SupportCorrespondence { get; set; }
        public virtual DbSet<SupportImages> SupportImages { get; set; }
        public virtual DbSet<SupportNew> SupportNew { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TicketViewDates> TicketViewDates { get; set; }
        public virtual DbSet<UserChangeStatus> UserChangeStatus { get; set; }
        public virtual DbSet<UserComputer> UserComputer { get; set; }
        public virtual DbSet<UsersLoggedIn> UsersLoggedIn { get; set; }
        public virtual DbSet<UsersPhotos> UsersPhotos { get; set; }
        public virtual DbSet<UsersProperties> UsersProperties { get; set; }
        public virtual DbSet<UsersReview> UsersReview { get; set; }
        public virtual DbSet<UsersScore> UsersScore { get; set; }
        public virtual DbSet<UsersToUsers> UsersToUsers { get; set; }
        public virtual DbSet<UsersToUsersMessages> UsersToUsersMessages { get; set; }
        public virtual DbSet<UsersToUsersServicesPayments> UsersToUsersServicesPayments { get; set; }
        public virtual DbSet<Versions> Versions { get; set; }
        public virtual DbSet<WindowsServiceLogs> WindowsServiceLogs { get; set; }
        public virtual DbSet<SupplierToLanguages> SupplierToLanguages { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<DomainProperties> DomainProperties { get; set; }
        public virtual DbSet<DomainsList> DomainsList { get; set; }
    }
}
