//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminPages
    {
        public Nullable<int> AdminID { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public string PageName { get; set; }
        public Nullable<int> LoginId { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admins()
        {
            this.AdminsLogins = new HashSet<AdminsLogins>();
            this.SupportCorrespondence = new HashSet<SupportCorrespondence>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public string AdminName { get; set; }
        public string Passowrd { get; set; }
        public Nullable<byte> Permissions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminsLogins> AdminsLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportCorrespondence> SupportCorrespondence { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminsLogins
    {
        public int AdminID { get; set; }
        public int ID { get; set; }
        public System.DateTime DateIn { get; set; }
        public string IpAddress { get; set; }
        public string SessionId { get; set; }
    
        public virtual Admins Admins { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminToUsersNews
    {
        public int ID { get; set; }
        public System.DateTime DateIn { get; set; }
        public string FreeText { get; set; }
        public string BackColor { get; set; }
        public string ForeColor { get; set; }
        public Nullable<int> Font_size { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntiFraudLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Reason { get; set; }
        public string CCNumber { get; set; }
        public string ExpMonth { get; set; }
        public string ExpYear { get; set; }
        public string Cvv { get; set; }
        public byte Active { get; set; }
        public string IdNumber { get; set; }
        public string LastDigits { get; set; }
        public string Treatment { get; set; }
        public string IpAddress { get; set; }
        public string Country { get; set; }
        public Nullable<byte> Priority { get; set; }
        public string CCCountry { get; set; }
        public int CcDetailsID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLogs
    {
        public int ID { get; set; }
        public int LogType { get; set; }
        public int UserrID { get; set; }
        public string LogMessage { get; set; }
        public System.DateTime DateIn { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackList
    {
        public int SupplierID { get; set; }
        public int CustomerID { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockedUserNum
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<decimal> IdNumber { get; set; }
        public string IpAddress { get; set; }
        public string ReasonExplain { get; set; }
        public Nullable<int> DataInsertAdminID { get; set; }
        public Nullable<int> PurchasesStatus { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockIdNumber
    {
        public int ID { get; set; }
        public Nullable<decimal> IdNumber { get; set; }
        public Nullable<int> UserNum { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public string IpAddress { get; set; }
        public string ReasonExplain { get; set; }
        public decimal DataInsertAdminID { get; set; }
        public Nullable<byte> PurchasesStatus { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockIp
    {
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public int ID { get; set; }
        public byte BlockType { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> IdNumber { get; set; }
        public Nullable<int> PurchasesStatus { get; set; }
        public string ReasonExplain { get; set; }
        public Nullable<int> DataInsertAdminID { get; set; }
        public Nullable<int> DaysToBlock { get; set; }
        public int EmployeeID { get; set; }
        public string CcNumber { get; set; }
        public int BlockStatus { get; set; }
        public string RemoveFromBlockReason { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardCam
    {
        public System.DateTime OrderDay { get; set; }
        public string Price { get; set; }
        public int ID { get; set; }
        public string SiteName { get; set; }
        public string IpAddress { get; set; }
        public decimal TimeExpire { get; set; }
        public string Lastdigits { get; set; }
        public string SubSite { get; set; }
        public System.DateTime OriginalDate { get; set; }
        public int UserID { get; set; }
        public byte UserAskToDelete { get; set; }
        public byte AdminShow { get; set; }
        public Nullable<byte> RegisterGift { get; set; }
        public Nullable<byte> WinGame { get; set; }
        public string UserGuid { get; set; }
        public string TransactionID { get; set; }
        public string AmountCurrency { get; set; }
        public string Subpid { get; set; }
        public Nullable<System.Guid> Pid { get; set; }
        public Nullable<decimal> AffiliateCut { get; set; }
        public string DomainName { get; set; }
        public Nullable<int> NetPrice { get; set; }
        public string ScratchingCardsId { get; set; }
        public string Referer { get; set; }
        public string Referrer { get; set; }
        public string TransactionProcessor { get; set; }
        public Nullable<byte> NoRealPayment { get; set; }
        public Nullable<byte> ECommerceGateDebited { get; set; }
        public Nullable<byte> ECommerceGateDebitedTrying { get; set; }
        public string OrderId { get; set; }
        public Nullable<byte> DiscoveryOffer { get; set; }
        public string Country { get; set; }
        public string CCCountry { get; set; }
        public string InatecTransactionid { get; set; }
        public string InatecTransactionStatus { get; set; }
        public Nullable<int> ShowInAdmin { get; set; }
        public Nullable<byte> BuyFromSub { get; set; }
        public Nullable<int> SubscriptionsPurchasesId { get; set; }
        public Nullable<byte> JacS { get; set; }
        public int CcDetailsID { get; set; }
        public Nullable<byte> CopyToLog { get; set; }
        public Nullable<byte> PaymentStatus { get; set; }
    
        public virtual CcDetails CcDetails { get; set; }
        public virtual Users Users { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCData
    {
        public string CCNumber { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime DateIn { get; set; }
        public byte Status { get; set; }
        public int Id { get; set; }
        public int SuspiciousAmount { get; set; }
        public string ReasonExplain { get; set; }
        public Nullable<int> DataInsertAdminID { get; set; }
        public string IpAddress { get; set; }
        public Nullable<decimal> IdNumber { get; set; }
        public string EncryptCard { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CcDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CcDetails()
        {
            this.CardCam = new HashSet<CardCam>();
        }
    
        public string CardNumber { get; set; }
        public string IdNumber { get; set; }
        public string YearDate { get; set; }
        public string MonthDate { get; set; }
        public string Cvv { get; set; }
        public int UserID { get; set; }
        public int ID { get; set; }
        public string LastDigits { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<int> Active { get; set; }
        public string CardToken { get; set; }
        public string TransactionProcessor { get; set; }
        public string EnglishName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EncryptCard { get; set; }
        public string Email { get; set; }
        public Nullable<int> CheapOfferUsed { get; set; }
        public string AdminData { get; set; }
        public byte IsPreAutorize { get; set; }
        public string EncryptIDNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardCam> CardCam { get; set; }
        public virtual Users Users { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatTimeUse
    {
        public int TimeUse { get; set; }
        public int ID { get; set; }
        public System.DateTime DateIn { get; set; }
        public System.DateTime Dateout { get; set; }
        public int SupplierID { get; set; }
        public Nullable<System.Guid> RndNum { get; set; }
        public int CustomerID { get; set; }
        public bool SessionStatus { get; set; }
        public int UserAskToDelete { get; set; }
        public byte UserValidate { get; set; }
        public byte FullCharge { get; set; }
        public byte BehindScreens { get; set; }
        public byte SendMessage { get; set; }
        public Nullable<decimal> MultiplySum { get; set; }
        public string EndError { get; set; }
        public string PlayerReferrer { get; set; }
        public Nullable<byte> VersionNum { get; set; }
        public Nullable<int> SessionMinTime { get; set; }
        public Nullable<double> PricePerMinute { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public byte RemoveStartTime { get; set; }
        public Nullable<int> PerformerSeeTimeUse { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<byte> CloseDiscount { get; set; }
        public double PerformerDiscount { get; set; }
        public Nullable<byte> TheChatWasActive { get; set; }
        public Nullable<System.DateTime> TheChatWasActiveDateIn { get; set; }
        public System.Guid ChatTimeUseGuid { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public int Id { get; set; }
        public string CountryEn { get; set; }
        public string CountryHe { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryList
    {
        public string CountryName { get; set; }
        public int ID { get; set; }
        public int TimeZoneID { get; set; }
        public int CurrencyID { get; set; }
        public int LanguageID { get; set; }
        public Nullable<double> SiteRevenue { get; set; }
        public string CountryCode { get; set; }
        public string Lc { get; set; }
        public string DefaultCountryCode { get; set; }
        public string CultureInfo { get; set; }
        public string INphonePrefix { get; set; }
        public int SiteMessageID { get; set; }
    
        public virtual Currencies Currencies { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currencies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Currencies()
        {
            this.CountryList = new HashSet<CountryList>();
        }
    
        public int ID { get; set; }
        public string CurrencySymbol { get; set; }
        public string CurrencyName { get; set; }
        public double MultipleFromDollar { get; set; }
        public string CurrencySide { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountryList> CountryList { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomainsList
    {
        public int ID { get; set; }
        public string DomainName { get; set; }
        public int DomainTypeID { get; set; }
        public string LogoName { get; set; }
        public string FacebookAppID { get; set; }
        public string FacebookSecret { get; set; }
        public string FacebookButton { get; set; }
        public int CategoryLevel { get; set; }
        public int MainCountryID { get; set; }
        public string Direction { get; set; }
        public string TextAlign { get; set; }
        public string FriendlyName { get; set; }
        public int CustomSearch { get; set; }
        public string Phone { get; set; }
        public string LiveChat { get; set; }
        public byte IsActive { get; set; }
        public byte CustomerDepositePercents { get; set; }
        public string ImageSize { get; set; }
        public int ShowNewsletter { get; set; }
        public int LanguageID { get; set; }
        public double Revenu { get; set; }
        public byte FreeDelivery { get; set; }
        public byte ShowSaleButton { get; set; }
        public byte ShowCountrySelection { get; set; }
        public byte Shop { get; set; }
        public byte SignIn { get; set; }
        public byte ShowPriceMainPage { get; set; }
        public byte ShowSearchBox { get; set; }
        public string MetaDescription { get; set; }
        public string SMSSenderID { get; set; }
        public Nullable<int> DnxCustomerID { get; set; }
        public int TemplateID { get; set; }
        public string Googletagmanager { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeManageLevels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeManageLevels()
        {
            this.Employees = new HashSet<Employees>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.SupportCorrespondence = new HashSet<SupportCorrespondence>();
        }
    
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime DateIn { get; set; }
        public int ManageLevel { get; set; }
        public byte Active { get; set; }
    
        public virtual EmployeeManageLevels EmployeeManageLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportCorrespondence> SupportCorrespondence { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Languages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Languages()
        {
            this.SiteMessagesToLanguages = new HashSet<SiteMessagesToLanguages>();
        }
    
        public int ID { get; set; }
        public string Language { get; set; }
        public string LocalLanguage { get; set; }
        public string CurrentCulture { get; set; }
    
        public virtual Languages Languages1 { get; set; }
        public virtual Languages Languages2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteMessagesToLanguages> SiteMessagesToLanguages { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCcFaild
    {
        public Nullable<decimal> IdNumber { get; set; }
        public string LastDigits { get; set; }
        public string ErrorNum { get; set; }
        public System.DateTime DateIn { get; set; }
        public int ColNum { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Email { get; set; }
        public string CardNumber { get; set; }
        public string YearDate { get; set; }
        public string MonthDate { get; set; }
        public string Cvv { get; set; }
        public string TransactionProcessor { get; set; }
        public string IpAddress { get; set; }
        public Nullable<byte> Status { get; set; }
        public string CCCountry { get; set; }
        public string Country { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogChatTimeUse
    {
        public int TimeUse { get; set; }
        public int ID { get; set; }
        public System.DateTime DateIn { get; set; }
        public System.DateTime Dateout { get; set; }
        public int SupplierID { get; set; }
        public Nullable<System.Guid> RndNum { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> SessionStatus { get; set; }
        public Nullable<int> UserAskToDelete { get; set; }
        public Nullable<byte> UserValidate { get; set; }
        public Nullable<byte> FullCharge { get; set; }
        public Nullable<byte> BehindScreens { get; set; }
        public Nullable<byte> SendMessage { get; set; }
        public Nullable<decimal> MultiplySum { get; set; }
        public Nullable<byte> UserConnectToGirlFMS { get; set; }
        public Nullable<byte> IsTablet { get; set; }
        public Nullable<byte> VersionNum { get; set; }
        public string PlayerReferrer { get; set; }
        public string EndError { get; set; }
        public byte RemoveStartTime { get; set; }
        public Nullable<int> PerformerSeeTimeUse { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogLastVisit
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public byte Gender { get; set; }
        public System.DateTime DateIn { get; set; }
        public byte Status { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogRtc
    {
        public int ID { get; set; }
        public int ChatTimeUseID { get; set; }
        public System.DateTime DateIn { get; set; }
        public string SupplierID { get; set; }
        public string CustomerID { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotsAboutCustomers
    {
        public int ID { get; set; }
        public System.DateTime DateIn { get; set; }
        public string Note { get; set; }
        public int SupplierID { get; set; }
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string IdNumber { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineUsers
    {
        public int Online { get; set; }
        public int SupplierID { get; set; }
        public System.DateTime Lastvisit { get; set; }
        public System.DateTime Ulastvisit { get; set; }
        public int CustomerID { get; set; }
        public System.Guid RndNumber { get; set; }
        public int GetUserGettingSendUser { get; set; }
        public int LastCustomerID { get; set; }
        public System.DateTime LastStatusChange { get; set; }
        public byte AdminAlert { get; set; }
        public byte FreeChat { get; set; }
        public System.DateTime TimeTheChatStart { get; set; }
        public byte NewTip { get; set; }
        public int SumUserTime { get; set; }
        public int IsQA { get; set; }
        public System.Guid UserTmpGuid { get; set; }
        public int GetUserApproveSendUser { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentStatus
    {
        public int SaleID { get; set; }
        public string PriceAmount { get; set; }
        public string TruncatedPAN { get; set; }
        public System.DateTime DateIn { get; set; }
        public string EventType { get; set; }
        public Nullable<int> UserNum { get; set; }
        public string ReferenceID { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformersPhotos
    {
        public string PhotoGuid { get; set; }
        public System.DateTime DateIn { get; set; }
        public int PhotoId { get; set; }
        public int SupplierID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrepaidBin
    {
        public int ID { get; set; }
        public string Bin { get; set; }
        public System.DateTime DateIn { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        public int Id { get; set; }
        public Nullable<int> PriceILS { get; set; }
        public Nullable<int> TimeExpire { get; set; }
        public string TextHE { get; set; }
        public string DiscountText { get; set; }
        public Nullable<byte> PriceStatus { get; set; }
        public Nullable<int> PriceEUR { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomConversation
    {
        public int ID { get; set; }
        public int SendUserID { get; set; }
        public int SupplierID { get; set; }
        public string Conversation { get; set; }
        public System.DateTime DateIn { get; set; }
        public bool WhoSend { get; set; }
        public byte GetUserRead { get; set; }
        public byte SendUserRead { get; set; }
        public System.Guid RndNumber { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendUsersWriteAboutGetUsers
    {
        public System.DateTime DateIn { get; set; }
        public int ID { get; set; }
        public int SupplierID { get; set; }
        public string FreeText { get; set; }
        public int SendUserID { get; set; }
        public Nullable<decimal> IdNumber { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int UsersActive { get; set; }
        public string UserMessage { get; set; }
        public int ID { get; set; }
        public decimal PaySumParam { get; set; }
        public System.DateTime WindowsServiceLastUpdate { get; set; }
        public string UserAppVersion { get; set; }
        public Nullable<int> UserAppForceVesion { get; set; }
        public int VideoResoultionWidth { get; set; }
        public int VideoResoultionHeight { get; set; }
        public int FramePerSecond { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMessages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiteMessages()
        {
            this.SiteMessagesToLanguages = new HashSet<SiteMessagesToLanguages>();
        }
    
        public int ID { get; set; }
        public string Message { get; set; }
        public System.DateTime DateIn { get; set; }
        public Nullable<int> DataType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteMessagesToLanguages> SiteMessagesToLanguages { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMessagesToLanguages
    {
        public int ID { get; set; }
        public string Message { get; set; }
        public Nullable<int> SiteMessageID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
    
        public virtual Languages Languages { get; set; }
        public virtual SiteMessages SiteMessages { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSLogs
    {
        public int ID { get; set; }
        public string PhoneNumber { get; set; }
        public string Answer { get; set; }
        public System.DateTime DateIn { get; set; }
        public string Processor { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Studios()
        {
            this.SupportChat = new HashSet<SupportChat>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public string FreeText { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<byte> Active { get; set; }
        public string Name { get; set; }
        public string Iban { get; set; }
        public string Swift { get; set; }
        public string RealName { get; set; }
        public Nullable<int> PhoneFeed { get; set; }
        public Nullable<int> ShiftBonus { get; set; }
        public Nullable<int> PercentageToModels { get; set; }
        public int OpenCall { get; set; }
        public int CreateCall { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportChat> SupportChat { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudiosToGirls
    {
        public Nullable<int> SupplierID { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<int> StudioNum { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportChat
    {
        public int ID { get; set; }
        public int StudioID { get; set; }
        public string ChatText { get; set; }
        public System.DateTime DateIn { get; set; }
        public byte IsAdmin { get; set; }
    
        public virtual Studios Studios { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportCorrespondence
    {
        public int Id { get; set; }
        public System.DateTime DateIn { get; set; }
        public int SupportId { get; set; }
        public string Cmessage { get; set; }
        public byte WhoSend { get; set; }
        public string SGuid { get; set; }
        public int SupplierID { get; set; }
        public string Img { get; set; }
        public byte HasImages { get; set; }
        public int EmployeeID { get; set; }
        public string Sms { get; set; }
    
        public virtual Admins Admins { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual SupportNew SupportNew { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportImages
    {
        public int ID { get; set; }
        public int SupportCorrespondenceID { get; set; }
        public string ImgName { get; set; }
        public System.DateTime DateIn { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportNew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupportNew()
        {
            this.SupportCorrespondence = new HashSet<SupportCorrespondence>();
            this.TicketViewDates = new HashSet<TicketViewDates>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateIn { get; set; }
        public byte Department { get; set; }
        public string Cmessage { get; set; }
        public string SGuid { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public byte IsReadCustomer { get; set; }
        public Nullable<byte> IsReadSupport { get; set; }
        public byte TicketsStatus { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Topic { get; set; }
        public string IpAddress { get; set; }
        public byte AdminHide { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public int DomainsListID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> NewID { get; set; }
        public int OrderID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportCorrespondence> SupportCorrespondence { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketViewDates> TicketViewDates { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketViewDates
    {
        public int ID { get; set; }
        public int SupportNewID { get; set; }
        public System.DateTime DateIn { get; set; }
    
        public virtual SupportNew SupportNew { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChangeStatus
    {
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public int GirlChangeStatusId { get; set; }
        public Nullable<int> NewStatus { get; set; }
        public Nullable<int> LastStatus { get; set; }
        public Nullable<int> QType { get; set; }
        public Nullable<int> GirlNotActiveTime { get; set; }
        public Nullable<int> UserFatal { get; set; }
        public Nullable<System.Guid> GirlRndNum { get; set; }
        public Nullable<int> UserNotActiveTime { get; set; }
        public string SpName { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComputer
    {
        public Nullable<int> CustomerID { get; set; }
        public string Os { get; set; }
        public Nullable<System.Guid> Fatal { get; set; }
        public Nullable<int> GetUserID { get; set; }
        public string Ip { get; set; }
        public string UserAgent { get; set; }
        public string Domain { get; set; }
        public int Id { get; set; }
        public string Browser { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<byte> SupportCamera { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.AntiFraudLog = new HashSet<AntiFraudLog>();
            this.AppLogs = new HashSet<AppLogs>();
            this.BlackList = new HashSet<BlackList>();
            this.BlackList1 = new HashSet<BlackList>();
            this.BlockedUserNum = new HashSet<BlockedUserNum>();
            this.BlockIdNumber = new HashSet<BlockIdNumber>();
            this.BlockIp = new HashSet<BlockIp>();
            this.CardCam = new HashSet<CardCam>();
            this.CCData = new HashSet<CCData>();
            this.CcDetails = new HashSet<CcDetails>();
            this.ChatTimeUse = new HashSet<ChatTimeUse>();
            this.ChatTimeUse1 = new HashSet<ChatTimeUse>();
            this.LogCcFaild = new HashSet<LogCcFaild>();
            this.LogChatTimeUse = new HashSet<LogChatTimeUse>();
            this.LogChatTimeUse1 = new HashSet<LogChatTimeUse>();
            this.LogLastVisit = new HashSet<LogLastVisit>();
            this.NotsAboutCustomers = new HashSet<NotsAboutCustomers>();
            this.OnlineUsers1 = new HashSet<OnlineUsers>();
            this.PerformersPhotos = new HashSet<PerformersPhotos>();
            this.RoomConversation = new HashSet<RoomConversation>();
            this.RoomConversation1 = new HashSet<RoomConversation>();
            this.SendUsersWriteAboutGetUsers = new HashSet<SendUsersWriteAboutGetUsers>();
            this.SendUsersWriteAboutGetUsers1 = new HashSet<SendUsersWriteAboutGetUsers>();
            this.SupportNew = new HashSet<SupportNew>();
            this.UserComputer = new HashSet<UserComputer>();
            this.UserComputer1 = new HashSet<UserComputer>();
            this.UsersLoggedIn = new HashSet<UsersLoggedIn>();
            this.UsersReview = new HashSet<UsersReview>();
            this.UsersReview1 = new HashSet<UsersReview>();
            this.UsersScore1 = new HashSet<UsersScore>();
            this.UsersScore2 = new HashSet<UsersScore>();
            this.UsersToUsers = new HashSet<UsersToUsers>();
            this.UsersToUsers1 = new HashSet<UsersToUsers>();
            this.WindowsServiceLogs = new HashSet<WindowsServiceLogs>();
            this.WindowsServiceLogs1 = new HashSet<WindowsServiceLogs>();
        }
    
        public string Name { get; set; }
        public System.DateTime DateIn { get; set; }
        public string Password { get; set; }
        public int Active { get; set; }
        public int ID { get; set; }
        public string IdPhoto { get; set; }
        public string Phone { get; set; }
        public string SendPayment { get; set; }
        public string Email { get; set; }
        public string Pic1 { get; set; }
        public string Pic2 { get; set; }
        public string Pic3 { get; set; }
        public string AdminDetails { get; set; }
        public string ExtraDetails { get; set; }
        public Nullable<int> YearBirth { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Referrer { get; set; }
        public Nullable<decimal> UsersScore { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<byte> DemoPerformer { get; set; }
        public Nullable<int> StudioId { get; set; }
        public string IpAddress { get; set; }
        public string CommunicationDetails { get; set; }
        public Nullable<int> PaymentsMethod { get; set; }
        public Nullable<byte> AdminApprovedCard { get; set; }
        public Nullable<byte> MinSessionLength { get; set; }
        public Nullable<double> PricePerMinute { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<byte> SmsActivation { get; set; }
        public Nullable<int> SmsCode { get; set; }
        public string CountryCode { get; set; }
        public System.Guid MainModelGuid { get; set; }
        public string FToken { get; set; }
        public string RealName { get; set; }
        public string PaymentsInformation { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string City { get; set; }
        public Nullable<byte> IsSupplier { get; set; }
        public string GenerateNumber { get; set; }
        public byte NeedUpdate { get; set; }
        public System.Guid UserChatGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AntiFraudLog> AntiFraudLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppLogs> AppLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlackList> BlackList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlackList> BlackList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockedUserNum> BlockedUserNum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockIdNumber> BlockIdNumber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockIp> BlockIp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardCam> CardCam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCData> CCData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CcDetails> CcDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatTimeUse> ChatTimeUse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatTimeUse> ChatTimeUse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogCcFaild> LogCcFaild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogChatTimeUse> LogChatTimeUse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogChatTimeUse> LogChatTimeUse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogLastVisit> LogLastVisit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotsAboutCustomers> NotsAboutCustomers { get; set; }
        public virtual OnlineUsers OnlineUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineUsers> OnlineUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformersPhotos> PerformersPhotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomConversation> RoomConversation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomConversation> RoomConversation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SendUsersWriteAboutGetUsers> SendUsersWriteAboutGetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SendUsersWriteAboutGetUsers> SendUsersWriteAboutGetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportNew> SupportNew { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserComputer> UserComputer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserComputer> UserComputer1 { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersLoggedIn> UsersLoggedIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersReview> UsersReview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersReview> UsersReview1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersScore> UsersScore1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersScore> UsersScore2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersToUsers> UsersToUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersToUsers> UsersToUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WindowsServiceLogs> WindowsServiceLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WindowsServiceLogs> WindowsServiceLogs1 { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersLoggedIn
    {
        public System.DateTime DateIn { get; set; }
        public int ID { get; set; }
        public int UserID { get; set; }
        public string IpAddress { get; set; }
        public Nullable<bool> Gender { get; set; }
        public byte Success { get; set; }
        public string BrowserDetails { get; set; }
        public string Password { get; set; }
        public string SessionID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersReview
    {
        public int CustomerID { get; set; }
        public int SupplierID { get; set; }
        public int ID { get; set; }
        public string FreeText { get; set; }
        public System.DateTime DateIn { get; set; }
        public int Activate { get; set; }
        public string FreeTextEn { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersScore
    {
        public int SupplierID { get; set; }
        public System.DateTime DateIn { get; set; }
        public Nullable<double> Score { get; set; }
        public string IpAddress { get; set; }
        public int ID { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersToUsers
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int SupplierID { get; set; }
        public System.DateTime DateIn { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersToUsersMessages
    {
        public int ID { get; set; }
        public System.DateTime DateIn { get; set; }
        public int CustomerID { get; set; }
        public int SupplierID { get; set; }
        public string MessageText { get; set; }
        public byte MessageRead { get; set; }
        public byte SendUserDelete { get; set; }
        public byte GetUserDelete { get; set; }
        public byte SenderDeleteForAll { get; set; }
        public byte MustRead { get; set; }
        public byte MessageType { get; set; }
        public string VideoImage { get; set; }
        public string MessageGuid { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WindowsServiceLogs
    {
        public int ID { get; set; }
        public int SupplierID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime DateIn { get; set; }
        public string EventDesc { get; set; }
        public string RndNumber { get; set; }
        public int IsError { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
